### PR TITLE
Bump io.swagger:swagger-codegen version to 2.2.3

### PR DESCRIPTION
**Pull request by vineethtw**
- Considering that there has been a new release of the swagger-codegen plugin, could we use the newer version in gradle plugin please?

### CODE REVIEW

**Comment by jbaldassari** [comment]
Should bump the plugin version as well.  ```1.7.2```?  ```1.8.0```?

**Comment by thebignet** [comment]
Tests fail but I haven't been able to take a look.  Did you check the failing tests ?  I know only the swagger version number has been modified but maybe there is more to it.

**Comment by thebignet** [comment]
Tests seem to work on my machine.  I'm merging this before uploading a new version.

**Comment by thebignet** [comment]
Version 1.7.2 of plugin should use swagger codegen 2.2.3

**Pull request merged**
